language: php
php:
- '7.2'
- '7.3'
addons:
  ssh_known_hosts:
    - 45.79.213.53
install:
- bash ./scripts/ci/install_php_modules.sh
- composer install
before_script:
- phpenv config-rm xdebug.ini || echo "No XDebug config"
- PATH=$PATH:$PWD/vendor/bin
- bash ./scripts/ci/generate_app_config_decoy.sh
- phpcbf --standard=PSR12 FileRegistry/Functions/ Models/ Classes/ Validation/ Functions/
  Utils/ config/ assign amend contacts schedule-recipients special-events
script:
- phan
- phpcs --standard=PSR1,PSR2,PSR12 FileRegistry/Functions/ Models/ Validation/
- phpcs --standard=PSR12 Functions/ Utils/ Classes/ config/
- phpcs --standard=PSR12 assign amend contacts schedule-recipients special-events
- phpunit
notifications:
  email: 
before_install:
- openssl aes-256-cbc -K $encrypted_90f812165a60_key -iv $encrypted_90f812165a60_iv
  -in scripts/scheduler-deploy.enc -out scripts/scheduler-deploy -d
- eval "$(ssh-agent -s)"
- cp scripts/scheduler-deploy ~/.ssh/scheduler-deploy
- chmod 600 ~/.ssh/scheduler-deploy
- ssh-add ~/.ssh/scheduler-deploy
- echo -e "Host 45.79.213.53\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
deploy:
- provider: script
  skip_cleanup: true
  script: bash scripts/deploy.sh
  on:
    branch: staging
