language: php

php:
  - '7.2'

install:
  - ./bin/ci/install_php_modules.sh
  - composer install

before_script:
  - phpenv config-rm xdebug.ini

script:
  - vendor/bin/phan

notifications:
  email:
    - e.fortmeyer01@gmail.com
