language: php
php: 7.3
addons:
  ssh_known_hosts:
    - $STAGING_HOST
before_install:
  - openssl aes-256-cbc -K $encrypted_90f812165a60_key -iv $encrypted_90f812165a60_iv -in scripts/scheduler-deploy.enc -out scripts/scheduler-deploy -d
  - eval "$(ssh-agent -s)"
  - cp scripts/scheduler-deploy ~/.ssh/scheduler-deploy
  - chmod 600 ~/.ssh/scheduler-deploy
  - ssh-add ~/.ssh/scheduler-deploy
  - echo -e "Host $STAGING_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
install:
  - bash ./build/install_php_modules.sh
  - composer -q install
before_script:
  - phpenv config-rm xdebug.ini || echo "No XDebug config"
  - PATH=$PATH:$PWD/vendor/bin
  - bash ./build/generate_app_config_decoy.sh
jobs:
  include:
    - stage: analysis-and-unit-testing
      php: 7.3
      script:
        - phpcbf --standard=PSR12 FileRegistry/Functions/ Models/ Classes/ Validation/ Functions/
          Utils/ config/ assign amend contacts schedule-recipients special-events
        - phpcs --standard=PSR1,PSR2,PSR12 FileRegistry/Functions/ Models/ Validation/
        - phpcs --standard=PSR12 Functions/ Utils/ Classes/ config/
        - phpcs --standard=PSR12 assign amend contacts schedule-recipients special-events
        - phan
        - phpunit --testsuite default
    - stage: pre-production-testing
      php: 7.3
      script:
        - php -d sendmail_path=./vendor/bin/smtp-mock-server.php ./vendor/bin/phpunit --testsuite integration
        - phpunit --testsuite end-to-end
    - stage: pre-production-deploy
      php: 7.3
      script:
        - bash ./build/pre-production-deploy.sh $STAGING_HOST $STAGING_USER
        - ssh $STAGING_USER@$STAGING_HOST "cd /home/$STAGING_USER/staging && bash ./build/run-tests.sh"
stages:
  - name: analysis-and-unit-testing
    if: branch = develop AND branch = master
  - name: pre-production-testing
    if: branch = staging
  - name: pre-production-deploy
    if: branch = staging
deploy:
- provider: script
  skip_cleanup: true
  script: bash ./build/production-deploy.sh $STAGING_HOST $STAGING_USER
  on:
    branch: master
notifications:
  email: false
