language: php

php:
  - '7.2'
  - '7.3'

install:
  - ./bin/ci/install_php_modules.sh
  - composer install

before_script:
  - phpenv config-rm xdebug.ini || echo "No XDebug config"

script:
  - vendor/bin/phan
  - vendor/bin/phpcs --standard=PSR1,PSR2,PSR12 FileRegistry/Functions/ config/ Models/ Validation/
  - vendor/bin/phpcs --standard=PSR12 Functions/ Utils/
  - vendor/bin/phpcs --standard=PSR12 assign
  - vendor/bin/phpunit

notifications:
  email:
    # - e.fortmeyer01@gmail.com
