language: php
php:
  - 7.2
  - 7.3
  # - nightly
# matrix:
  # allow_failures:
    # - php: nightly
addons:
  ssh_known_hosts:
    - 45.79.213.53
before_install:
  - openssl aes-256-cbc -K $encrypted_90f812165a60_key -iv $encrypted_90f812165a60_iv -in scripts/scheduler-deploy.enc -out scripts/scheduler-deploy -d
  - eval "$(ssh-agent -s)"
  - cp scripts/scheduler-deploy ~/.ssh/scheduler-deploy
  - chmod 600 ~/.ssh/scheduler-deploy
  - ssh-add ~/.ssh/scheduler-deploy
  - echo -e "Host 45.79.213.53\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
install:
  - bash ./scripts/ci/install_php_modules.sh
  - composer -q install
before_script:
  - phpenv config-rm xdebug.ini || echo "No XDebug config"
  - PATH=$PATH:$PWD/vendor/bin
  - bash ./scripts/ci/generate_app_config_decoy.sh
jobs:
  include:
    - stage: testing
      matrix:
        include:
          - php: nightly
          -  os:
              - linux
              - windows
        allow_failures:
          - php: nightly
          - os: windows
      script:
        - phpcbf --standard=PSR12 FileRegistry/Functions/ Models/ Classes/ Validation/ Functions/
          Utils/ config/ assign amend contacts schedule-recipients special-events
        - phpcs --standard=PSR1,PSR2,PSR12 FileRegistry/Functions/ Models/ Validation/
        - phpcs --standard=PSR12 Functions/ Utils/ Classes/ config/
        - phpcs --standard=PSR12 assign amend contacts schedule-recipients special-events
        - phpunit --testsuite default
        - phan
stages:
  - name: testing
    if: branch = develop
staging:
  provider: script
  script:
    - phpunit --testsuite integration
    - phpunit --testsuite end-to-end
  on:
    branch: staging
deploy:
  provider: script
  skip_cleanup: true
  script: bash scripts/deploy.sh
  on:
    branch: master
