#!/usr/bin/env php
<?php

use function StudentAssignmentScheduler\Functions\CLI\green;
use function StudentAssignmentScheduler\Functions\CLI\red;


if (!key_exists(1, $argv)) {
    $message = PHP_EOL
        . "When using the import command, please indicate the type of item that will be imported." . PHP_EOL
        . "This is done on the by using this format when entering the command:" . PHP_EOL
        . "import <type>" . PHP_EOL . PHP_EOL;
    exit($message);
}
$type = $argv[1];

[$config, $paths] = require "bootstrap.php";

array_map(
    function (string $file) use ($paths, $type) {
        $dest = __DIR__ . "/{$paths["path_to_${type}"]}/" . basename($file);
        copy($file, $dest) ? success($file, $dest) : fail($file);
        $result = copy($file, $dest);
    },
    array_filter(
        $argv,
        function($key) {
            return $key != 0 && $key != 1;
        },
        ARRAY_FILTER_USE_KEY
    )
);

function success(string $file, string $dest): void
{
    print green("Imported ${file}\r\nDestination: ${dest}\r\n");
}

function fail(string $file): void
{
    print red("Failed to import ${file}\r\n");
    exit();
}
