#!/usr/bin/env php
<?php declare(strict_types=1);

namespace StudentAssignmentScheduler\CLI\Commands\Resend;

use PHPMailer\PHPMailer\PHPMailer;
use Dotenv\Dotenv;
use StudentAssignmentScheduler\{
    ListOfContacts,
    Contact,
    Notification\MailSender,
    DocumentProduction\PdfAssignmentFormWriter
};
use \Ds\{
    Set,
    Vector,
    Map
};
use function StudentAssignmentScheduler\Bootstrapping\Functions\{
    buildPath,
    setupKeys,
    decryptedPassword
};
use function StudentAssignmentScheduler\Querying\Functions\{
    getContacts,
    getScheduleRecipients
};
use function StudentAssignmentScheduler\CLI\setupEmail;

[$config, $path_config, $config_file] = require "bootstrap.php";
// setup email and secret keys if they haven't already been setup
try {
    $path_to_secrets = buildPath(__DIR__, "data", "secrets");
    $env_dir = __DIR__;
    $email_vars = [
        "from_email",
        "from_email_password",
        "from_email_nonce",
        "from_email_key",
        "smtp_host",
    ];
    $secrets_vars = [
        "m",
        "s"
    ];
    $Dotenv = new Dotenv($env_dir);
    $Dotenv->load();
} catch (\Dotenv\Exception\InvalidPathException $e) {
    setupEmail($env_dir); // user interaction
    setupKeys($path_to_secrets, $env_dir);
    $Dotenv->load();
}

try {
    $Dotenv->required($email_vars);
} catch (\Dotenv\Exception\ValidationException $e) {
    setupEmail($env_dir);
    $Dotenv->load();
}

try {
    $Dotenv->required($secrets_vars);
} catch (\Dotenv\Exception\ValidationException $e) {
    setupKeys($path_to_secrets, $env_dir);
    $Dotenv->load();
}
$contacts_dir = buildPath(__DIR__, "data", "contacts");
$contacts_file = buildPath($contacts_dir, "contacts");
$schedule_recipients_file = buildPath($contacts_dir, "schedule_recipients");

$ListOfContacts = getContacts(
    $contacts_file,
    getenv("m"),
    getenv("s")
);
$ListOfScheduleRecipients = getScheduleRecipients(
    $schedule_recipients_file,
    getenv("m"),
    getenv("s")
);

$email = getenv("from_email");
$passwd = decryptedPassword();
$host = getenv("smtp_host");

$command = (new Map($argv))->get(1, "");

$MailSender = new MailSender(
    new PHPMailer(true),
    $email,
    $passwd,
    $host
);
$AssignmentFormWriter = new PdfAssignmentFormWriter($config);

$orDefault = function () {
    showManPage();
};
$selectedCommand = commandMap()->get($command, $orDefault);

$selectedCommand($MailSender, $ListOfContacts, $config, $ListOfScheduleRecipients, $AssignmentFormWriter);
