#!/usr/bin/env php
<?php

namespace StudentAssignmentScheduler\CLI\Commands\Contacts;

use \Dotenv\Dotenv;
use \Ds\Map;
use function StudentAssignmentScheduler\{
    Bootstrapping\buildPath,
    Bootstrapping\setupKeys,
    Encryption\masterKey,
    Encryption\secretKey,
    Encryption\unbox
};

require "bootstrap.php";

try {
    $path_to_secrets = buildPath(__DIR__, "data", "secrets");
    $env_dir = __DIR__;
    $secrets_vars = [
        "m",
        "s"
    ];
    $Dotenv = new Dotenv($env_dir);
    $Dotenv->load();
} catch (\Dotenv\Exception\InvalidPathException $e) {
    setupKeys($path_to_secrets, $env_dir);
    $Dotenv->load();
}

try {
    $Dotenv->required($secrets_vars);
} catch (\Dotenv\Exception\ValidationException $e) {
    setupKeys($path_to_secrets, $env_dir);
    $Dotenv->load();
}

$contacts_dir = buildPath(__DIR__, "data", "contacts");
$contacts_file = buildPath($contacts_dir, "schedule_recipients");

$command = (new Map($argv))->get(1, "");


$key = secretKey(
    getenv("s"),
    masterKey(getenv("m"))
);

main($contacts_file, $key, $command);
