#!/usr/bin/env php
<?php declare(strict_types=1);

namespace StudentAssignmentScheduler;

use PHPMailer\PHPMailer\PHPMailer;
use Dotenv\Dotenv;
use StudentAssignmentScheduler\{
    ListOfContacts,
    Contact,
    Fullname,
    Notification\MailSender
};
use \Ds\{
    Set,
    Vector
};
use function StudentAssignmentScheduler\{
    Bootstrapping\buildPath,
    Bootstrapping\setupKeys,
    CLI\setupEmail
};

[$config, $path_config, $config_file] = require "bootstrap.php";
// setup email and secret keys if they haven't already been setup
try {
    $path_to_secrets = buildPath(__DIR__, "data", "secrets");
    $env_dir = __DIR__;
    $secrets_vars = [
        "m",
        "s"
    ];
    $Dotenv = new Dotenv($env_dir);
    $Dotenv->load();
} catch (\Dotenv\Exception\InvalidPathException $e) {
    setupEmail($env_dir); // user interaction
    setupKeys($path_to_secrets, $env_dir);
    exit();
}

try {
    $Dotenv->required($secrets_vars);
} catch (\Dotenv\Exception\ValidationException $e) {
    setupKeys($path_to_secrets, $env_dir);
    $Dotenv->load();
}
setupEmail($env_dir);
