#!/usr/bin/env php
<?php declare(strict_types=1);

namespace StudentAssignmentScheduler\CLI\Commands\SpecialEvents;

use \Ds\Map;

require "bootstrap.php";

$command = (new Map($argv))->get(1, "");

main($command);
