#!/usr/bin/env php
<?php

namespace StudentAssignmentScheduler\Functions\CLI\Commands\SpecialEvents;

use \Ds\Map;

require "bootstrap.php";

$command = (new Map($argv))->get(1, "");

main($command);
