#!/usr/bin/env php
<?php

use function StudentAssignmentScheduler\Functions\{
    createFile,
    importJson,
    Logging\fileSaveLogger,
    CLI\displayList
};

use StudentAssignmentScheduler\Guid;

require_once __DIR__ . "/../autoload.php";

$filename_of_app_config = __DIR__ . "/../config/app_config.json";

$daysOfWeek = [
    "Sunday",
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday"
];
$available_languages = ["ASL"];

$previous_config = file_exists($filename_of_app_config) ? importJson($filename_of_app_config) : [];
$app_id = key_exists("app_id", $previous_config) ? new Guid($previous_config["app_id"]) : new Guid();

displayList($daysOfWeek);
$meeting_night_index = readline("Select the number to the left of the day of your weekly meeting: ");
$meeting_night = $daysOfWeek[$meeting_night_index];
print "You selected ${meeting_night}" . PHP_EOL . PHP_EOL;

displayList($available_languages);
$language_index = readline("Select the number to the left of the language of your weekly meeting: ");
$language = $available_languages[$language_index];
print "You selected ${language}" . PHP_EOL . PHP_EOL;

$config_obj = new class($app_id, $meeting_night, $language) {
    public $app_id;
    public $language;
    public $meeting_night;
    public function __construct(Guid $app_id, string $meeting_night, string $language)
    {
        $this->app_id = (string) $app_id;
        $this->meeting_night = $meeting_night;
        $this->language = $language;
    }
};

$logger = fileSaveLogger("createFile");
createFile($config_obj, $filename_of_app_config, $logger);

print "You're all set!" . PHP_EOL . PHP_EOL;
